language: perl
sudo: false
env:
    global:
        - PERL_MONGO_WITH_ASSERTS=1
services:
  - mongodb
install:
  - cpanm -n -q --skip-satisfied Config::AutoConf Path::Tiny
  - cpanm -n -q --skip-satisfied --installdeps .
script: perl Makefile.PL && make test
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
