---
type: single
default_args: -v --noprealloc --nojournal --smallfiles --nohttpinterface --nssize 6 --setParameter authenticationMechanisms=SCRAM-SHA-1
default_version: v3.0
auth:
    user: root
    password: toor
mongod:
    - name: host1
