---
type: replica
setName: foo
default_args: -v --nojournal --bind_ip 0.0.0.0 --quiet --storageEngine=inMemoryExperiment
mongod:
    - name: host1
    - name: host2
    - name: host3
      rs_config:
          arbiterOnly: true

# vim: ts=4 sts=4 sw=4 et:
