---
type: replica
setName: foo
default_args: -v --nojournal --nohttpinterface --quiet --storageEngine=wiredTiger
mongod:
    - name: host1
    - name: host2
    - name: host3
      rs_config:
          arbiterOnly: true

# vim: ts=4 sts=4 sw=4 et:
