---
type: replica
setName: foo
default_args: -v --bind_ip 0.0.0.0 --noprealloc --nojournal --smallfiles --nssize 6 --quiet
ssl_config:
    mode: requireSSL
    servercn: "CN=localhost,OU=Server,O=MongoDB,L=New York,ST=New York,C=US"
    certs:
        server: devel/certs/server.pem
        ca: devel/certs/ca.pem
mongod:
    - name: host1
    - name: host2
    - name: host3
      rs_config:
          arbiterOnly: true

# vim: ts=4 sts=4 sw=4 et:
