---
type: replica
setName: foo
default_args: -v --noprealloc --nojournal --smallfiles --nohttpinterface --nssize 6 --quiet
auth:
    user: root
    password: toor
mongod:
    - name: host1
    - name: host2
    - name: host3
      rs_config:
          priority: 0
          hidden: true

# vim: ts=4 sts=4 sw=4 et:
