---
type: replica
setName: foo
default_args: -v --noprealloc --nojournal --smallfiles --bind_ip 0.0.0.0 --nssize 6 --quiet
mongod:
    - name: host1
      port_override: 27017
    - name: host2
    - name: host3
      rs_config:
          arbiterOnly: true

# vim: ts=4 sts=4 sw=4 et:
