---
type: sharded
default_args: -v --nohttpinterface --quiet
default_version: 3.4
mongoc:
    - name: config1
    - name: config2
    - name: config3
mongos:
    - name: router1
shards:
    - name: sh1
      type: single
      mongod:
          - name: db1
            args: --enableMajorityReadConcern
# vim: ts=4 sts=4 sw=4 et:
