---
type: sharded
default_args: -v --noprealloc --smallfiles --nohttpinterface --nssize 6 --quiet
mongoc:
    - name: config1
    - name: config2
    - name: config3
mongos:
    - name: router1
shards:
    - name: sh1
      type: single
      mongod:
          - name: db1
# vim: ts=4 sts=4 sw=4 et:
