---
type: sharded
default_args: -v --nojournal --bind_ip 0.0.0.0 --quiet --storageEngine=inMemoryExperiment
mongoc:
    - name: config1
mongos:
    - name: router1
shards:
    - name: sh1
      type: single
      mongod:
          - name: db1
# vim: ts=4 sts=4 sw=4 et:
